module SettingsGame
  SLEEP_INTERVAL = 0.5
  WAITING_INPUT = 0.1
  TIMING_BLOKING = 0.4
  

  FIELD_WIDTH = 12
  FIELD_HEIGHT = 21

  FIELD_WIDTH_GAMING = FIELD_WIDTH - 2
  FIELD_HEIGHT_GAMING = FIELD_HEIGHT - 1
end